version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data from company gz sportwear 
    tables:
      - name: product
        identifier: raw_gz_product
        description: stock of products
      - name: sales
        identifier: raw_gz_sales
        description: list of all sales and orders
      - name: ship
        identifier: raw_gz_ship
        description: list with all shipping status
